CREATE DATABASE QLBH
ON PRIMARY (NAME = 'QLBH', FILENAME = 'D:\SQL\QLBH.mdf',SIZE=16,MAXSIZE=UNLIMITED,FILEGROWTH=32)
LOG ON (NAME = 'QLBH_log', FILENAME = 'D:\SQL\QLBH.ldf',SIZE=16,MAXSIZE=UNLIMITED,FILEGROWTH=32)

GO
USE QLBH

CREATE TABLE CongTy(MaCT NVARCHAR(20) NOT NULL CONSTRAINT PK_CongTy PRIMARY KEY, TenCT NCHAR(20), TrangThai NCHAR(10), ThanhPho NCHAR(20))
CREATE TABLE SanPham(MaSP NVARCHAR(20) NOT NULL CONSTRAINT PK_SanPham PRIMARY KEY, TenSP NCHAR(20) UNIQUE, MauSac NCHAR(20) DEFAULT N'Đỏ', Gia MONEY, SoLuongCo INT )
CREATE TABLE CungUng(MaCT NVARCHAR(20) NOT NULL CONSTRAINT FK_CU_CT FOREIGN KEY(MaCT) REFERENCES dbo.CongTy(MaCT), MaSP NVARCHAR(20) NOT NULL CONSTRAINT FK_CU_SP FOREIGN KEY(MaSP) REFERENCES dbo.SanPham(MaSP), SoLuongBan INT CONSTRAINT CHK_SL CHECK (SoLuongBan>0))